spring:
  application:
    name: ms-books-catalogue


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


  elasticsearch:
    host: ${ELASTICSEARCH_HOST}
    credentials:
      user: ${ELASTICSEARCH_USER}
      password: ${ELASTICSEARCH_PWD}
    logging:
      level:
        tracer: TRACE

